Repository YosysHQ/yosys, pull requests merged in 2024-04, with the labels that each got.

#4295 add port statistics to stat command
  passes/cmds/stat.cc
Labels: merge-soon

#4273 verific: Improve import VHDL constants
  frontends/verific/verific.cc
Labels: merge-before-release

#4302 Verific support for VHDL 2019
  frontends/verific/Makefile.inc
  frontends/verific/verific.cc
Labels: merge-before-release

#4338 formalff -setundef: Fix handling for has_srst FFs
  passes/sat/formalff.cc
Labels: merge-after-jf

#4285 Typo fixing
  frontends/ast/genrtlil.cc
  kernel/driver.cc
  passes/pmgen/ice40_dsp.cc
  techlibs/anlogic/synth_anlogic.cc
  techlibs/ecp5/synth_ecp5.cc
  techlibs/efinix/synth_efinix.cc
  techlibs/fabulous/synth_fabulous.cc
  techlibs/gowin/synth_gowin.cc
  techlibs/ice40/synth_ice40.cc
  techlibs/lattice/synth_lattice.cc
  techlibs/nexus/synth_nexus.cc
Labels: merge-soon

#4333 fix hierarchy -generate mode handling of cells
  passes/hierarchy/hierarchy.cc
  tests/various/hierarchy_generate.ys
Labels: merge-soon
