Repository YosysHQ/yosys, pull requests merged in 2024-05, with the labels that each got.

#4321 read_verilog: Add missing defaults for flags
  frontends/verilog/verilog_frontend.cc
Labels: merge-after-jf

#4377 smtbmc: Improvements for --incremental and .yw fixes
  backends/smt2/smtbmc.py
  backends/smt2/smtbmc_incremental.py
  backends/smt2/smtio.py
Labels: check-sby

#4404 box_derive: New command to derive modules for boxes
  passes/cmds/Makefile.inc
  passes/cmds/box_derive.cc
  passes/cmds/select.cc
  tests/various/box_derive.ys
Labels: merge-soon
