Repository YosysHQ/yosys, pull requests merged in 2024-10, with the labels that each got.

#4553 -y flag for libyosys Python scripts
  kernel/driver.cc
Labels: merge-before-release

#4613 log: Never silence `log_cmd_error`
  kernel/log.cc
  tests/various/logger_cmd_error.sh
Labels: merge-before-release

#4624 cxxrtl: test stream operator
  tests/cxxrtl/test_value.cc
Labels: merge-after-jf

#4376 Docs: Use formatted cmd ref in pdf
  .github/workflows/test-build.yml
  Makefile
  docs/Makefile
  docs/source/index.rst
  docs/source/using_yosys/synthesis/synth.rst
  kernel/register.cc
Labels: merge-soon

#4668 actions: vendor sources with submodules for releases
  .github/workflows/source-vendor.yml
  .gitmodules
  README.md
Labels: merge-after-jf
