Repository YosysHQ/yosys, pull requests merged in 2024-11, with the labels that each got.

#4543 libs/fst: Update from upstream
  Makefile
  libs/fst/00_PATCH_win_io.patch
  libs/fst/00_PATCH_win_zlib.patch
  libs/fst/00_UPDATE.sh
  libs/fst/fastlz.cc
  libs/fst/fst_win_unistd.h
  libs/fst/fstapi.cc
  libs/fst/fstapi.h
  libs/fst/lz4.cc
  libs/fst/lz4.h
Labels: merge-soon

#4680 Makefile: add -rdynamic on macOS to fix plugins with LTO
  Makefile
Labels: merge-before-release

#4679 readme: tell macOS users to use brew clang with LTO
  README.md
Labels: merge-before-release

#4719 add select option for write_json
  backends/json/json.cc
Labels: discuss

#4721 kernel/drivertools.h: avoid maybe-uninitialized compile warnings
  kernel/drivertools.h
Labels: merge-after-jf
