Repository YosysHQ/yosys, pull requests merged in 2025-06, with the labels that each got.

#5170 Revert log_debug back to macro from function
  kernel/log.h
Labels: merge-before-release

#5159 Fix `proc` handling of whiteboxes
  passes/proc/proc_arst.cc
  passes/proc/proc_clean.cc
  passes/proc/proc_dff.cc
  passes/proc/proc_dlatch.cc
  passes/proc/proc_init.cc
  passes/proc/proc_memwr.cc
  passes/proc/proc_mux.cc
  passes/proc/proc_prune.cc
  passes/proc/proc_rmdead.cc
  passes/proc/proc_rom.cc
  passes/techmap/abc9_ops.cc
Labels: merge-before-release

#5172 Suppress several spurious warnings
  frontends/verific/verific.cc
  kernel/rtlil.cc
  passes/hierarchy/hierarchy.cc
Labels: merge-before-release

#5152 verilog: implement SystemVerilog unique/unique0/priority if semantics.
  docs/source/cell/word_mux.rst
  docs/source/yosys_internals/verilog.rst
  frontends/verilog/verilog_parser.y
  tests/proc/case_attr.ys
  tests/verilog/unique_priority_case.ys
  tests/verilog/unique_priority_if.ys
Labels: merge-soon

#5160 verilog: improve string literal matching speed (fixes #5076)
  frontends/verilog/verilog_lexer.l
Labels: merge-after-release

#5165 opt_dff: don't remove cells until all have been visited to prevent UAF
  passes/opt/opt_dff.cc
  tests/opt/bug5164.ys
Labels: merge-soon

#5173 Allows calling yosys_shutdown and then yosys_setup to restart.
  kernel/yosys.cc
Labels: merge-after-jf
