Repository YosysHQ/yosys, pull requests merged in 2025-05, with the labels that each got.

#5085 verilog_parser.y: Delete unused TOK_ID
  frontends/verilog/verilog_parser.y
  tests/verilog/param_default.ys
Labels: merge-soon

#5078 Change the implementation of log_debug in kernel/log.h
  kernel/log.h
Labels: merge-after-release

#5086 driver: add --no-version to suppress writing Yosys version
  backends/aiger/aiger.cc
  backends/aiger/xaiger.cc
  backends/blif/blif.cc
  backends/btor/btor.cc
  backends/edif/edif.cc
  backends/jny/jny.cc
  backends/json/json.cc
  backends/rtlil/rtlil_backend.cc
  backends/smt2/smt2.cc
  backends/smv/smv.cc
  backends/spice/spice.cc
  backends/verilog/verilog_backend.cc
  kernel/driver.cc
  kernel/register.cc
  kernel/yosys.cc
  kernel/yosys.h
  kernel/yosys_common.h
  passes/cmds/internal_stats.cc
  passes/cmds/stat.cc
  passes/sat/sat.cc
  passes/sat/sim.cc
Labels: merge-soon

#5108 Create a single-port URAM mapping to support memories 2048 x 144b
  techlibs/xilinx/urams.txt
  techlibs/xilinx/urams_map.v
  tests/arch/xilinx/priority_memory.v
  tests/arch/xilinx/priority_memory.ys
Labels: merge-soon

#5089 cutpoint: Re-add whole module optimization
  passes/sat/cutpoint.cc
  tests/various/cutpoint_whole.ys
Labels: merge-soon

#5112 design.cc: Use on_shutdown method
  kernel/register.h
  passes/cmds/design.cc
Labels: merge-soon

#5123 Strip trailing slashes when checking for directories on Windows.
  kernel/io.cc
Labels: merge-soon

#5127 Disable STRIP operations when appropriate.
  Makefile
Labels: merge-after-jf

#5141 Accept (and ignore) SystemVerilog unique/priority if.
  docs/source/yosys_internals/verilog.rst
  frontends/verilog/verilog_parser.y
  kernel/constids.inc
  tests/verilog/priority_if_enc.ys
  tests/verilog/unique0_if_enc.ys
  tests/verilog/unique_if.ys
  tests/verilog/unique_if_else.ys
  tests/verilog/unique_if_else_begin.ys
  tests/verilog/unique_if_enc.ys
Labels: merge-soon

#5143 SystemVerilog: Fix typedef struct in global space
  frontends/ast/simplify.cc
  frontends/verilog/verilog_parser.y
  tests/svtypes/typedef_struct_global.ys
Labels: merge-soon
