Repository YosysHQ/yosys, pull requests merged in 2025-03, with the labels that each got.

#4827 Update ALU MULT mode in gowin to match nextpnr
  techlibs/gowin/cells_sim.v
Labels: merge-soon

#4898 write_xaiger: Detect and error on combinatorial loops
  backends/aiger/xaiger.cc
Labels: merge-soon

#4818 Add `$macc_v2`
  docs/source/cell/word_arith.rst
  docs/source/code_examples/fifo/fifo.ys
  docs/source/getting_started/example_synth.rst
  kernel/celledges.cc
  kernel/celltypes.h
  kernel/consteval.h
  kernel/constids.inc
  kernel/macc.h
  kernel/rtlil.cc
  kernel/rtlil.h
  kernel/satgen.cc
  passes/techmap/booth.cc
  passes/techmap/maccmap.cc
  passes/techmap/techmap.cc
  techlibs/common/simlib.v
  techlibs/common/techmap.v
  tests/alumacc/basic.ys
  tests/alumacc/macc_infer_n_unmap.ys
Labels: merge-after-release

#4567 cxxrtl: use octal encoding of non-printables.
  backends/cxxrtl/cxxrtl_backend.cc
  kernel/fmt.cc
Labels: merge-soon

#4922 splitcells: Fix the assertion bug caused by out-of-bound offset
  passes/cmds/splitcells.cc
  tests/various/bug4909.ys
Labels: merge-soon

#4926 Verilog file list suport
  .gitignore
  frontends/verific/verific.cc
  frontends/verilog/verilog_frontend.cc
Labels: merge-soon

#4904 share: add -pattern-limit to limit analysis effort
  passes/opt/share.cc
Labels: merge-before-release

#4941 docs: Add latex magic to make PDFs reproducible again
  docs/source/conf.py
Labels: merge-soon

#4834 Memory-efficient zlib usage across Liberty file consumers
  Makefile
  backends/btor/btor.cc
  backends/smt2/smt2.cc
  frontends/verific/verific.cc
  kernel/gzip.cc
  kernel/gzip.h
  kernel/io.cc
  kernel/io.h
  kernel/register.cc
  kernel/utils.h
  kernel/yosys.cc
  kernel/yosys_common.h
  passes/cmds/stat.cc
  passes/fsm/fsm_recode.cc
  passes/opt/peepopt.cc
  passes/opt/pmux2shiftx.cc
  passes/opt/wreduce.cc
  passes/pmgen/pmgen.py
  passes/sat/assertpmux.cc
  passes/techmap/clockgate.cc
  passes/techmap/dfflibmap.cc
  tests/various/stat.ys
Labels: merge-soon

#4940 mk: Avoid broken rebuild if program --help fails
  Makefile
Labels: merge-soon

#4677 opt_merge: hashing performance and correctness
  passes/opt/opt_merge.cc
  tests/opt/opt_merge_basic.ys
Labels: enhancement, merge-soon

#4953 A few fixes, mostly local docs builds
  docs/source/conf.py
  docs/source/getting_started/installation.rst
  docs/source/yosys_internals/extending_yosys/test_suites.rst
  libs/fst/00_PATCH_i386_endian.patch
  libs/fst/00_UPDATE.sh
  libs/fst/fstapi.cc
Labels: merge-soon
